### ISSUE TITLE
winget missing URL

### ISSUE THREAD

**Issue by mariuslindegard** [BrammyS/necesse-docker-server#75]
**To Reproduce**
1. clone repo
2. docker build . -t "necesse-server"

Console:
 => [base 1/4] FROM docker.io/library/alpine:3@sha256:b89d9c93e9ed3597455c90a0b88a8bbb5cb7188438f70953fede212a0c4394e0                                                                                 0.0s
 => CACHED [base 2/4] RUN apk --update add wget unzip                                                                                                                                                  0.0s
 => CACHED [base 3/4] RUN apk add openjdk8 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community                                                                                            0.0s
 => CACHED [base 4/4] RUN rm -rf /var/cache/apk/*                                                                                                                                                      0.0s
 => ERROR [build 1/3] RUN wget ${url}                                                                                                                                                                  0.8s
------
 > [build 1/3] RUN wget ${url}:
0.517 wget: missing URL
0.517 Usage: wget [OPTION]... [URL]...
0.517
0.517 Try `wget --help' for more options.
------
Dockerfile:42
--------------------
  40 |
  41 |     # Install necesse server files.
  42 | >>> RUN wget ${url}
  43 |     RUN unzip necesse-server-linux64-${version}-${build}.zip
  44 |     RUN rm -rf ${dir}/jre
--------------------
ERROR: failed to solve: process "/bin/sh -c wget ${url}" did not complete successfully: exit code: 1

Raspberry Pi 4B

**Comment by BrammyS** [comment]
Seems like you are missing build args.
See the workflow file for the building of the image for an example.

```
      - name: Build and export to Docker hub
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            url=${{matrix.url}}
            version=${{matrix.version}}
            build=${{matrix.build}}
```

Or simply use the pre-build docker image: https://hub.docker.com/r/brammys/necesse-server
